services:
  - type: web
    plan: free # Paid plan example - change this to your purchased plan (e.g., free, starter, standard, professional)
    name: Rkn-AutoCaptionBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/RknDeveloper/Rkn-AutoCaptionBot.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: DEFAULT_CAPTION
        value: "<b><a href='https://t.me/Rkn_Botz'>{file_name} Main Telegram Channel: @Rkn_Bots_Updates</a></b>"
        sync: false
      - key: RKN_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: PORT
        value: "8080"
        sync: false